target("42_Compute_Water")
    set_group("Project 19-")
    set_kind("binary")
    set_targetdir(path.join(binDir, "42_Compute_Water"))
    add_dx_sdk_options()
    add_deps("ImGui")
    add_includedirs("../Common")
    add_files("../Common/d3dApp.cpp", "../Common/CpuTimer.cpp", "../Common/GpuTimer.cpp",
        "../Common/DXTrace.cpp", "../Common/ScreenGrab11.cpp")
    add_files("*.cpp")
    add_headerfiles("*.h", "Shaders/*.hlsl", "Shaders/*.hlsli")
    add_syslinks("windowscodecs", "ole32")
    local source_dir = os.scriptdir()
    after_build(function(target)
        os.cp(path.join(source_dir, "Shaders"), target:targetdir())
        os.cp(path.join(source_dir, "Assets"), target:targetdir())
    end)
target_end()
